# Generated by Django 3.2.20 on 2023-08-08 17:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_reference', models.SmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=5000)),
                ('abilities', models.CharField(max_length=2000)),
                ('stats', models.CharField(max_length=2000)),
                ('movements', models.TextField(max_length=5000)),
                ('image', models.CharField(max_length=2000)),
            ],
            options={
                'ordering': ['id_reference'],
            },
        ),
    ]
